### ISSUE TITLE
Update Stack

### ISSUE THREAD

**Issue by DevBaier** [carlrygart/portainer-stack-deploy#19]
Hi, 

very nice feature but i have a problem with the updating of stack. 
can it be that changing the config don't allow to update the stack or update only work if the image change.

Thank you

**Comment by carlrygart** [comment]
Hi!

Do you mean that the stack doesn’t get deployed if you try to deploy an unchanged stack definition?

**Comment by DevBaier** [comment]
Hi,

Im meaning that if i deploy changes it try to recreate the stack but it should update it.

**Comment by carlrygart** [comment]
Do you happen to change the stack name? The stack name is the unique identifier for each stack. If you change it in your stack definition it will create a new stack.

**Comment by DevBaier** [comment]
I dont change the stack name it says me that a stack with this name exist

**Comment by carlrygart** [comment]
So what’s the actual diff between deployments in the stack definition file?

**Comment by DevBaier** [comment]
Only the image is updated :D

**Comment by carlrygart** [comment]
Ah okay, then that's the problem. The way Portainer works is that if the stack definition (docker-compose file) is not changed it doesn't do anything when you deploy. It's by design by Portainer. Instead, I think they want you to use the "Update the service" button with the force download image option. If you're doing it in a pipeline I think the easiest is to use the Webhook.

Personally, I like having a unique tag/version for each version. In this way, it's easier to roll back if something goes wrong. Also if you happen to change something in the stack definition, you are sure it's going to be deployed. But ofc it might differ to your use-case.

**Comment by DevBaier** [comment]
Ok thank you
